spring:
  datasource:
    url: jdbc:h2:~/MBA/projects/spring/h2/acquirerdb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true