server:
  port: 8085
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autorizadora
    username: root
    password: Gringotts
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  security:
    user:
      name: username
      password: secret
      roles: USER
  mail:
    host: smtp.office365.com
    port: 587
    username: email@hotmail.com
    password: senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false    
jwt:
  secret: s3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14P
  expirationInSeconds: 1800