server:
  port: 8085

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:h2:~/MBA/projects/spring/h2/acquirerdb;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.office365.com
    port: 587
    username: email@hotmail.com
    password: senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
jwt:
  secret: s3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14Ps3cr37F14P
